--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-20-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence MEMBER_JJH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  YOUTUBE_MEMBER_JJH_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence YOUTUBE_JJH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  YOUTUBE_JJH_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 42 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence YOUTUBE_LIKE_JJH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  YOUTUBE_LIKE_JJH_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 176 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence YOUTUBE_REPLY_JJH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  YOUTUBE_REPLY_JJH_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 252 NOCACHE  NOORDER  NOCYCLE ;

------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-20-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table YOUTUBE_MEMBER_JJH
--------------------------------------------------------

  CREATE TABLE YOUTUBE_MEMBER_JJH
   (	MEM_IDX NUMBER,
	MEM_ID VARCHAR2(50 BYTE),
	MEM_NAME VARCHAR2(50 BYTE),
	MEM_PWD VARCHAR2(50 BYTE),
	MEM_AUTH VARCHAR2(50 BYTE),
	MEM_GENDER VARCHAR2(50 BYTE),
	MEM_PHONE VARCHAR2(50 BYTE),
	MEM_EMAIL VARCHAR2(50 BYTE),
	REGIST_DATE DATE,
	UPDATE_DATE DATE,
	REGIST_ID VARCHAR2(50 BYTE),
	UPDATE_ID VARCHAR2(50 BYTE),
	REGIST_IP VARCHAR2(50 BYTE),
	UPDATE_IP VARCHAR2(50 BYTE),
	MEM_IP VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table YOUTUBE_JJH
--------------------------------------------------------

  CREATE TABLE YOUTUBE_JJH
   (	NUM NUMBER,
	TITLE VARCHAR2(50 BYTE),
	WRITER VARCHAR2(50 BYTE),
	CONTENT VARCHAR2(4000 BYTE),
	REGDATE DATE,
	CNT NUMBER DEFAULT 0,
	BOARD_IDX NUMBER(11,0),
	UPDATE_DATE DATE,
	WRITE_DATE DATE,
	BOARD_LIKE NUMBER(11,0),
	YOUTUBE_URL VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table YOUTUBE_LIKE_JJH
--------------------------------------------------------

  CREATE TABLE YOUTUBE_LIKE_JJH
   (	LIKE_IDX NUMBER(11,0),
	NUM NUMBER(11,0),
	MEM_IDX NUMBER(11,0)
   );
--------------------------------------------------------
--  DDL for Table YOUTUBE_REPLY_JJH
--------------------------------------------------------

  CREATE TABLE YOUTUBE_REPLY_JJH
   (	REPLY_IDX NUMBER(11,0),
	REPLY_CONTENT VARCHAR2(1000 BYTE),
	REPLY_REGDATE DATE,
	NUM NUMBER,
	MEM_IDX NUMBER(11,0)
   );
REM INSERTING into YOUTUBE_MEMBER_JJH
SET DEFINE OFF;
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (2,'admin','운영자','123123','member','남성',null,null,to_date('22/12/28','RR/MM/DD'),to_date('22/12/29','RR/MM/DD'),null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (3,'피카츄','파이리','123123','member','여성',null,null,to_date('22/12/28','RR/MM/DD'),to_date('22/12/29','RR/MM/DD'),null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (4,'test123','홍길동','123123','member',null,null,null,to_date('23/01/07','RR/MM/DD'),null,null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (5,'admin222','홍길동','123123','member','남성',null,null,to_date('23/01/07','RR/MM/DD'),null,null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (6,'test77','홍길동','123123','member','남성','010-1234-1234','naver22@naver.com',to_date('23/01/07','RR/MM/DD'),to_date('23/01/07','RR/MM/DD'),null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (7,'test2','홍길동','123123','member','남성','010-1234-1234','naver@naver.com',to_date('23/01/07','RR/MM/DD'),null,null,null,null,null,'0:0:0:0:0:0:0:1');
Insert into YOUTUBE_MEMBER_JJH (MEM_IDX,MEM_ID,MEM_NAME,MEM_PWD,MEM_AUTH,MEM_GENDER,MEM_PHONE,MEM_EMAIL,REGIST_DATE,UPDATE_DATE,REGIST_ID,UPDATE_ID,REGIST_IP,UPDATE_IP,MEM_IP) values (8,'youtube','test','123123','member','남성','010-1234-1234','test@test.com',to_date('23/01/20','RR/MM/DD'),null,null,null,null,null,'0:0:0:0:0:0:0:1');
REM INSERTING into YOUTUBE_JJH
SET DEFINE OFF;
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (37,'youtube','admin','test',to_date('23/01/13','RR/MM/DD'),32,null,null,to_date('23/01/13','RR/MM/DD'),null,'https://youtu.be/kGwOj9xbF_8');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (38,'음악','admin','test test test test test test
test test test test test test test test test test test test test test ',to_date('23/01/13','RR/MM/DD'),491,null,to_date('23/01/13','RR/MM/DD'),to_date('23/01/19','RR/MM/DD'),null,'https://youtu.be/tWL_s_IJMDQ');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (39,'z2','admin','test2',to_date('23/01/16','RR/MM/DD'),15,null,to_date('23/01/19','RR/MM/DD'),null,null,'https://youtu.be/hbk1twmxzF4');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (41,'test11','youtube','test11',to_date('23/01/20','RR/MM/DD'),3,null,null,null,null,'https://youtu.be/tWL_s_IJMDQ');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (27,'유튜브','admin','123',to_date('23/01/10','RR/MM/DD'),22,null,to_date('23/01/10','RR/MM/DD'),null,null,'https://youtu.be/sVTy_wmn5SU');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (23,'test11','admin','test',to_date('23/01/10','RR/MM/DD'),11,null,null,to_date('23/01/10','RR/MM/DD'),null,'https://youtu.be/tWL_s_IJMDQ');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (28,'뉴진스 뮤비','admin','뉴진스 뮤비입니다.',to_date('23/01/10','RR/MM/DD'),4,null,null,to_date('23/01/10','RR/MM/DD'),null,'https://youtu.be/11cta61wi0g');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (29,'무한도전','admin','123123',to_date('23/01/10','RR/MM/DD'),4,null,null,to_date('23/01/10','RR/MM/DD'),null,'https://youtu.be/5gEgBSf106Y');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (30,'아는 형님','admin',null,to_date('23/01/10','RR/MM/DD'),6,null,null,to_date('23/01/11','RR/MM/DD'),null,'https://youtu.be/MIkQXCWjQhA');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (33,'음악추천','admin','123',to_date('23/01/10','RR/MM/DD'),54,null,to_date('23/01/10','RR/MM/DD'),null,null,'https://youtu.be/rTi9R2XUd6A');
Insert into YOUTUBE_JJH (NUM,TITLE,WRITER,CONTENT,REGDATE,CNT,BOARD_IDX,UPDATE_DATE,WRITE_DATE,BOARD_LIKE,YOUTUBE_URL) values (32,'기분풀리는 노래','admin','노래',to_date('23/01/10','RR/MM/DD'),6,null,null,to_date('23/01/10','RR/MM/DD'),null,'https://youtu.be/wPDl_XuUGqY');
REM INSERTING into YOUTUBE_LIKE_JJH
SET DEFINE OFF;
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (150,33,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (141,21,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (174,39,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (146,27,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (151,17,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (152,37,2);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (164,38,3);
Insert into YOUTUBE_LIKE_JJH (LIKE_IDX,NUM,MEM_IDX) values (175,41,8);
REM INSERTING into YOUTUBE_REPLY_JJH
SET DEFINE OFF;
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (2,'77',to_date('23/01/02','RR/MM/DD'),19,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (3,'test',to_date('23/01/03','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (4,'123123',to_date('23/01/03','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (8,'test222',to_date('23/01/03','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (9,'123test',to_date('23/01/03','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (10,'안녕하세요 피카츄입니다.',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (11,'댓글22',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (12,'댓글22',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (13,'댓글33',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (14,'댓글44',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (15,'댓글5',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (16,'댓글6',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (17,'댓글7',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (18,'댓글8',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (19,'댓글9',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (20,'댓글10',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (21,'댓글11',to_date('23/01/03','RR/MM/DD'),20,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (22,'123123',to_date('23/01/04','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (23,'xxxxxs',to_date('23/01/04','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (24,'sdfsdf',to_date('23/01/04','RR/MM/DD'),20,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (25,'123123',to_date('23/01/04','RR/MM/DD'),19,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (83,'aaaaaaaaaaaaaa',to_date('23/01/05','RR/MM/DD'),18,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (136,'2',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (137,'3',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (135,'1',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (138,'피카츄입니다??',to_date('23/01/06','RR/MM/DD'),17,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (73,'DFEASDFE',to_date('23/01/05','RR/MM/DD'),18,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (139,'11',to_date('23/01/06','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (140,'asd',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (141,'dd',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (142,'ddddddddddddd',to_date('23/01/06','RR/MM/DD'),17,3);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (150,'zzzzz',to_date('23/01/07','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (146,'df',to_date('23/01/06','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (152,'1123',to_date('23/01/07','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (155,'123',to_date('23/01/07','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (154,'213',to_date('23/01/07','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (156,'123',to_date('23/01/07','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (195,'test',to_date('23/01/10','RR/MM/DD'),32,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (193,'test',to_date('23/01/10','RR/MM/DD'),27,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (194,'test2',to_date('23/01/10','RR/MM/DD'),27,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (196,'test',to_date('23/01/11','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (197,'test',to_date('23/01/11','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (198,'넷플릭스',to_date('23/01/11','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (199,'티빙',to_date('23/01/11','RR/MM/DD'),17,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (170,'1',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (171,'2',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (172,'3',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (173,'4',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (174,'5',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (175,'1',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (176,'ㅁㄴㅇ',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (177,'ㅁㄴㅇㅂㅂ',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (178,'ㄴㄴ',to_date('23/01/10','RR/MM/DD'),16,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (179,'1',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (180,'2',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (181,'3',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (182,'4',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (183,'5',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (184,'6',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (185,'7',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (186,'8',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (187,'9',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (188,'10',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (189,'11',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (190,'12',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (191,'13',to_date('23/01/10','RR/MM/DD'),8,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (200,'test',to_date('23/01/11','RR/MM/DD'),33,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (201,'test2',to_date('23/01/11','RR/MM/DD'),33,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (202,'test',to_date('23/01/11','RR/MM/DD'),33,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (203,'test3',to_date('23/01/11','RR/MM/DD'),33,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (204,'test4',to_date('23/01/11','RR/MM/DD'),33,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (205,'test1',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (206,'test2',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (207,'test3',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (208,'test4',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (209,'test5',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (211,'test6',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (212,'test7',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (213,'test8',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (214,'test9',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (215,'test10',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (219,'test13',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (217,'test11',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (218,'test12',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (220,'test14',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (221,'test15',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (222,'test16',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (223,'test17',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (224,'test18',to_date('23/01/19','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (225,'test19',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (226,'test20',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (227,'test21',to_date('23/01/13','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (228,'test22',to_date('23/01/16','RR/MM/DD'),38,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (249,'test1',to_date('23/01/20','RR/MM/DD'),41,8);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (245,'dd',to_date('23/01/17','RR/MM/DD'),37,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (246,'dfsf',to_date('23/01/17','RR/MM/DD'),37,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (248,'cc',to_date('23/01/19','RR/MM/DD'),39,2);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (250,'test2',to_date('23/01/20','RR/MM/DD'),41,8);
Insert into YOUTUBE_REPLY_JJH (REPLY_IDX,REPLY_CONTENT,REPLY_REGDATE,NUM,MEM_IDX) values (251,'test3',to_date('23/01/20','RR/MM/DD'),41,8);

--------------------------------------------------------
--  Constraints for Table YOUTUBE_MEMBER_JJH
--------------------------------------------------------

  ALTER TABLE YOUTUBE_MEMBER_JJH MODIFY (MEM_IDX NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_MEMBER_JJH MODIFY (MEM_ID NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_MEMBER_JJH MODIFY (MEM_NAME NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_MEMBER_JJH MODIFY (MEM_PWD NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_MEMBER_JJH ADD PRIMARY KEY (MEM_IDX);
--------------------------------------------------------
--  Constraints for Table YOUTUBE_LIKE_JJH
--------------------------------------------------------

  ALTER TABLE YOUTUBE_LIKE_JJH MODIFY (NUM NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_LIKE_JJH MODIFY (MEM_IDX NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_LIKE_JJH ADD PRIMARY KEY (LIKE_IDX);
--------------------------------------------------------
--  Constraints for Table YOUTUBE_REPLY_JJH
--------------------------------------------------------

  ALTER TABLE YOUTUBE_REPLY_JJH MODIFY (REPLY_CONTENT NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_REPLY_JJH MODIFY (REPLY_REGDATE NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_REPLY_JJH MODIFY (NUM NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_REPLY_JJH MODIFY (MEM_IDX NOT NULL ENABLE);
  ALTER TABLE YOUTUBE_REPLY_JJH ADD PRIMARY KEY (REPLY_IDX);
